name: walkapp
description: A simple step counter (pedometer) app. Ready for Codemagic.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^3.0.0
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
