name: walkapp
description: Adim sayar uygulamasi
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^3.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
